# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import mocri_pb2 as mocri__pb2


class MocriStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListModels = channel.unary_stream(
        '/mocri.Mocri/ListModels',
        request_serializer=mocri__pb2.ListModelsParams.SerializeToString,
        response_deserializer=mocri__pb2.OcrModelInfo.FromString,
        )
    self.BinarizeImage = channel.unary_unary(
        '/mocri.Mocri/BinarizeImage',
        request_serializer=mocri__pb2.BinarizationParams.SerializeToString,
        response_deserializer=mocri__pb2.Image.FromString,
        )
    self.SegmentLines = channel.unary_stream(
        '/mocri.Mocri/SegmentLines',
        request_serializer=mocri__pb2.LineSegmentationParams.SerializeToString,
        response_deserializer=mocri__pb2.Box.FromString,
        )
    self.RecognizeText = channel.unary_stream(
        '/mocri.Mocri/RecognizeText',
        request_serializer=mocri__pb2.RecognitionParams.SerializeToString,
        response_deserializer=mocri__pb2.OcrText.FromString,
        )


class MocriServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListModels(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BinarizeImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SegmentLines(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RecognizeText(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MocriServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListModels': grpc.unary_stream_rpc_method_handler(
          servicer.ListModels,
          request_deserializer=mocri__pb2.ListModelsParams.FromString,
          response_serializer=mocri__pb2.OcrModelInfo.SerializeToString,
      ),
      'BinarizeImage': grpc.unary_unary_rpc_method_handler(
          servicer.BinarizeImage,
          request_deserializer=mocri__pb2.BinarizationParams.FromString,
          response_serializer=mocri__pb2.Image.SerializeToString,
      ),
      'SegmentLines': grpc.unary_stream_rpc_method_handler(
          servicer.SegmentLines,
          request_deserializer=mocri__pb2.LineSegmentationParams.FromString,
          response_serializer=mocri__pb2.Box.SerializeToString,
      ),
      'RecognizeText': grpc.unary_stream_rpc_method_handler(
          servicer.RecognizeText,
          request_deserializer=mocri__pb2.RecognitionParams.FromString,
          response_serializer=mocri__pb2.OcrText.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'mocri.Mocri', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
